[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_UMAMI_WEBSITE_ID = "54ba9f61-ea93-41db-a5e1-3e74b41605da"
  HUGO_UMAMI_SCRIPT_URL = "https://cloud.umami.is/script.js"
  HUGO_UMAMI_DOMAINS = "christianguzman.uk"

[context.deploy-preview]
  command = "hugo --gc --minify --templateMetrics --templateMetricsHints --buildExpired --buildFuture --forceSyncStatic --baseURL \"$DEPLOY_PRIME_URL\""

[context.branch-deploy]
  command = "hugo --gc --minify --templateMetrics --templateMetricsHints --buildExpired --buildFuture --forceSyncStatic --baseURL \"$DEPLOY_PRIME_URL\""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/plugins/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
